### ISSUE TITLE
Tries to use Nightwatch runner with an undefined test source

### ISSUE THREAD

**Issue by JonWallsten** [mucsi96/nightwatch-cucumber#103]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
Outputs unhandled error when test is done, even though everything looks fine.

**Expected/desired behavior**
Should not output error when nothing is wrong.

**Reproduction of the problem**
Run any test with 1 or more features/steps. See the following output.
```
// console.log(testsource) @ C:\Repo\***\node_modules\nightwatch\lib\runner\run.js:170
[ 'C:\\Users\\***\\AppData\\Local\\Temp\\tmp-4992eP7C3iNJ6cjr\\test\\features' ]
Feature: Test chain of scenarios

  Scenario: Load game
  ✓ Given Game is started
  ✓ Then Game should be loaded

  Scenario: Turn off sound
  ✓ Given Sound is turned off
  ✓ Then Sound off icon should be visible

2 scenarios (2 passed)
4 steps (4 passed)
0m12.170s
// console.log(testsource) @ C:\Repo\***\node_modules\nightwatch\lib\runner\run.js:170
[ undefined ]
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'indexOf' of undefined
    at C:\Repo\***\node_modules\nightwatch\lib\runner\run.js:172:14
    at Array.map (native)
    at Function.Runner.readPaths (C:\Repo\***\node_modules\nightwatch\lib\runner\run.js:171:32)
    at Runner.runner (C:\Repo\***\node_modules\nightwatch\lib\runner\run.js:223:12)
    at Runner.<anonymous> (C:\Repo\***\node_modules\nightwatch-cucumber\lib\nightwatch-api.js:206:32)
    at next (native)
    at onFulfilled (C:\Repo\***\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7) } reason: TypeError: Cannot read property 'indexOf' of undefined
    at C:\Repo\***\node_modules\nightwatch\lib\runner\run.js:172:14
    at Array.map (native)
    at Function.Runner.readPaths (C:\Repo\***\node_modules\nightwatch\lib\runner\run.js:171:32)
    at Runner.runner (C:\Repo\***\node_modules\nightwatch\lib\runner\run.js:223:12)
    at Runner.<anonymous> (C:\Repo\***\node_modules\nightwatch-cucumber\lib\nightwatch-api.js:206:32)
    at next (native)
    at onFulfilled (C:\Repo\***\node_modules\co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
The root cause seems to be that an undefined path is sent to Nightwatch after the only Feature is complete. I do not have any other Features in any other files at the moment.

The following method is executed with testSource as _undefined_ when the test is complete.
```
Runner.readPaths = function(testSource, opts, cb) {
  var deferred = Q.defer();
  cb = cb || function() {};

  if (typeof testSource == 'string') {
    testSource = [testSource];
  }

  var fullPaths = testSource.map(function (p) {
    if (p.indexOf(process.cwd()) === 0 || path.resolve(p) === p) {
      return p;
    }
...
```

**What is the expected behavior?**
It should not try to call the runner with an undefined path.

**What is the motivation / use case for changing the behavior?**
The test never ends and has to be manually terminated in the command prompt.

**Please tell us about your environment:**
Windows 10 on parallels on a MacBook Pro
* **nightwatch-cucumber version:**
5.0.3
* **nightwatch version:**
0.9.8
* **cucumber version:**
2.3.0
* **Node.js version:**
6.6.0

**Comment by JonWallsten** [comment]
This is probably because of the combined runners, right? Maybe I need to update some commit.

**Comment by mucsi96** [comment]
Hi @JonWallsten,

Thanks for your feedback!
Can you provide your nightwatch configuration?

**Comment by JonWallsten** [comment]
Sure. Here it is:
```
const seleniumServer = require("selenium-server");
const chromedriver = require("chromedriver");
const path = require("path");

const cwd = process.cwd();

const FEATURES_PATH = "./test/features";
const STEP_DEFS_PATH = "./test/step_definitions";
const SCREENSHOT_PATH = "./reports/screenshots";

const CUSTOM_COMMANDS_PATHS = [
    path.join(__dirname, "src/commands"),
    path.join(__dirname, "src/commands/core"),
    path.join(__dirname, "src/commands/jmx")
];

const CUSTOM_ASSERTIONS_PATHS = [
    path.join(__dirname, "src/assertions")
];

// we use a nightwatch.conf.js file so we can include comments and helper functions
module.exports = {
    "src_folders": [require("nightwatch-cucumber")({
        "runner": "nightwatch",
        "featureFiles": FEATURES_PATH,
        "stepDefinitions": STEP_DEFS_PATH,
        "htmlReport": "./reports/index.html"
    })],
    "globals_path": path.join(cwd, "globals.js"),
    "custom_commands_path": CUSTOM_COMMANDS_PATHS,
    "custom_assertions_path": CUSTOM_ASSERTIONS_PATHS,
    "output_folder": false,
    "selenium": {
        "start_process": true,
        "server_path": seleniumServer.path,
        "host": "127.0.0.1",
        "port": 4444,
        "cli_args": {
            "webdriver.chrome.driver": chromedriver.path
        }
    },
    "test_settings": {
        "default": {
            "launch_url": "http://localhost",
            "selenium_port": 4444,
            "selenium_host": "127.0.0.1",
            "silent": true,
            "env": "default",
            "screenshots": {
                "enabled": true,
                "on_failure": true,
                "on_error": true,
                "path": SCREENSHOT_PATH
            },
            "desiredCapabilities": {
                "browserName": "chrome"
            }
        },
        "local": {
            "launch_url": "http://localhost",
            "selenium_port": 4444,
            "selenium_host": "127.0.0.1",
            "silent": true,
            "env": "local",
            "screenshots": {
                "enabled": true,
                "on_failure": true,
                "on_error": true,
                "path": SCREENSHOT_PATH
            },
            "desiredCapabilities": {
                "browserName": "chrome",
                "chromeOptions": {
                },
                "javascriptEnabled": true,
                "acceptSslCerts": true
            }
        },
        // your local chrome browser (chromedriver)
        "chrome": {
            "desiredCapabilities": {
                "browserName": "chrome",
                "javascriptEnabled": true,
                "acceptSslCerts": true
            }
        }
    }
};

```

**Comment by mucsi96** [comment]
You configuration is outdated. There was a configuration change in version 5. Please read the readme and the changelog. Hope this helps. I am closing the issue
