### ISSUE TITLE
Unable to change features location without breaking runner

### ISSUE THREAD

**Issue by roc** [mucsi96/nightwatch-cucumber#104]
**I'm submitting a**  
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**

Given this directory structure:

```
|  acceptance_tests
|  |  features
|  |  |  step_definitions
|  |  reports
|  |  screenshots
```

And this configuration (located at project root):

```
'use strict';

require('nightwatch-cucumber')();

module.exports = {
  // Old configuration from nightwatch-cucumber 4
  // src_folders: [require('nightwatch-cucumber')({
  //   featureFiles: 'acceptance_tests/features',
  //   stepDefinitions: 'acceptance_tests/features/step_definitions',
  //   htmlReport: 'acceptance_tests/reports/index.html'
  // })],
  featureFiles: ['acceptance_tests/features'],
  output_folder: 'acceptance_tests/reports',
  custom_commands_path: '',
  custom_assertions_path: '',
  page_objects_path: '',
  live_output: false,
  disable_colors: false,

  /** boilerplate config after this 
  ...
  **/
};
```

Running previously functioning acceptance tests now fails with:

```
$ ./node_modules/.bin/nightwatch

Starting selenium server... started - PID:  71137

Error: Cannot read source folder: /var/folders/g5/_c7mlh9j6pg4x8rg8b6278lr0000gn/T/tmp-71130W2FgZbcRQM1j/features
    at /node_modules/nightwatch/lib/runner/run.js:192:21
    at /node_modules/nightwatch/lib/runner/walk.js:97:18
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Expected/desired behavior**

Tests run as with nightwatch 4x, but with exciting new Scenario Tagging enabled etc

**Reproduction of the problem**

```
mkdir test
cd test
mkdir acceptance_tests/features
touch package.json
# I mean, whatever you want in here I guess? 😣
# {
#  "name": "nightwatch-cucumber-features",
#  "version": "0.0.0",
#  "description": "Quick test to show issue with folder locations ",
#  "main": "index.js"
# }
npm i cucumber nightwatch nightwatch-cucumber --save-dev

# add configuration as above
./node_modules/.bin/nightwatch
```

**Please tell us about your environment:**

```
$ nvm current
v4.2.2
$ npm -v
3.8.7
```

* **nightwatch-cucumber version:**

```
"devDependencies": {
  "cucumber": "^1.3.0",
  "nightwatch": "^0.9.8",
  "nightwatch-cucumber": "^5.0.5"
}
```

**Comment by mucsi96** [comment]
Hi @roc ,

I think this is a documentation issue. Because you misunderstood it  😄  The configuration for Nightwatch and configuration for nightwatch-cucumber is a separate thing currently. See the (configuration)[https://github.com/mucsi96/nightwatch-cucumber#configuration] section. Hope this helps

**Comment by mucsi96** [comment]
I created a ticket for creating a better error message for handling this miss-configuration. https://github.com/mucsi96/nightwatch-cucumber/issues/106.

**Comment by roc** [comment]
That's really helpful, thank you! 🙏 

Here's the full patch, which meant the update worked as expected:

```
diff --git a/nightwatch.conf.js b/nightwatch.conf.js
index f838348..0462079 100644
--- a/nightwatch.conf.js
+++ b/nightwatch.conf.js
@@ -14,23 +14,24 @@ const screenshotSettings = (folderName) => {
   };
 };

+require('nightwatch-cucumber')({
+  featureFiles: ['acceptance_tests/features'],
+  stepDefinitions: ['acceptance_tests/features/step_definitions'],
+  htmlReport: 'acceptance_tests/reports/index.html'
+});
+
 /* eslint camelcase: 0*/
 module.exports = {
-  src_folders: [require('nightwatch-cucumber')({
-    featureFiles: 'acceptance_tests/features',
-    stepDefinitions: 'acceptance_tests/features/step_definitions',
-    htmlReport: 'acceptance_tests/reports/index.html'
-  })],
   output_folder: 'acceptance_tests/reports',
   custom_commands_path: '',
   custom_assertions_path: '',
   page_objects_path: '',
   live_output: false,
   disable_colors: false,
```

Just in case that is at all useful to other (big fans!) people upgrading from `v4.0.0` to `v5.0.5`
