### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by hayesmaker** [mucsi96/nightwatch-cucumber#105]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**

If I start tests with command: `node_modules/.bin/nightwatch`

```
ERROR TypeError: Cannot read property 'run' of undefined
    at NightwatchApi.addTestRunner (/Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/node_modules/nightwatch-cucumber/lib/nightwatch-api.js:145:47)
    at Runner.run (/Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/node_modules/nightwatch-cucumber/lib/runner.js:111:24)
    at module.exports (/Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/node_modules/nightwatch-cucumber/lib/index.js:52:16)
    at Object.<anonymous> (/Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/test/e2e/nightwatch/nightwatch.conf.js:4:31)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
ERROR There was an error while starting the test runner:


Error: No testing environment specified.
    at Object.CliRunner.parseTestSettings (/Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/node_modules/nightwatch/lib/runner/cli/clirunner.js:442:13)
    at Object.CliRunner.setup (/Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/node_modules/nightwatch/lib/runner/cli/clirunner.js:49:8)
    at Object.exports.runner (/Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/node_modules/nightwatch/lib/index.js:546:17)
    at /Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/node_modules/nightwatch/bin/runner.js:9:16
    at Object.exports.cli (/Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/node_modules/nightwatch/lib/index.js:540:5)
    at Object.<anonymous> (/Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine/node_modules/nightwatch/bin/runner.js:8:14)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
```

my nightwatch conf:

```
var seleniumServer = require('selenium-server');
var chromedriver = require('chromedriver');

require('nightwatch-cucumber')();

module.exports = {
  output_folder: 'reports',
  custom_commands_path: './custom-commands/',
  custom_assertions_path: './custom-assertions/',
  globals_path: './globals/globals.js',
  live_output: false,
  disable_colors: false,

  selenium: {
    start_process: true,
    server_path: seleniumServer.path,
    log_path: '',
    host: '127.0.0.1',
    port: 4444
  },

  test_settings: {
    default: {
      launch_url: 'http://localhost',
      selenium_port: 4444,
      selenium_host: 'localhost',
      silent: true,
      screenshots: {
        enabled: true,
        on_failure: true,
        on_error: false,
        path: 'screenshots/default'
      }
    },

    chrome: {
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        acceptSslCerts: true
      },
      selenium: {
        cli_args: {
          'webdriver.chrome.driver': chromedriver.path
        }
      }
    }
  }
};

```

my installed cucumber version:

```
npm ls cucumber

casino-engine@7.2.6-postrelease /Users/hayesmaker/Workspace/contracts/high5/online/client_code/HTML5/CasinoEngine
└── cucumber@1.3.0
```

**Expected/desired behavior**

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **nightwatch-cucumber version:**

* **nightwatch version:**

* **cucumber version:**

* **Node.js version:**

**Comment by hayesmaker** [comment]
i just had to update nightwatch (my shrinkwrap was locking me to nightwatch v0.8.9)
