### ISSUE TITLE
Going through configuration in README I'm getting error `Cannot find module '<project_path>/node_modules/cucumber/lib/cucumber'`

### ISSUE THREAD

**Issue by arozwalak** [mucsi96/nightwatch-cucumber#155]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
After I installed `cucumber`, `nightwatch` and `nightwatch-cucumber`, I created `nightwatch.conf.js` file and set `nightwatch-cucumber` as described. I created sample test. But when I run nightwatch I'm getting error `Cannot find module '<project_path>/node_modules/cucumber/lib/cucumber'` and `There was an error while starting the test runner: Error: No testing environment specified.`

**nightwatch.conf.js**
```
const SCREENSHOT_PATH = "./screenshots/";
const BINPATH = './node_modules/nightwatch/bin/';

/**
 * selenium-download does exactly what it's name suggests;
 * downloads (or updates) the version of Selenium (& chromedriver)
 * on your localhost where it will be used by Nightwatch.
 /the following code checks for the existence of `selenium.jar` before trying to run our tests.
 */

require('fs').stat(BINPATH + 'selenium.jar', function (err, stat) { // got it?
  if (err || !stat || stat.size < 1) {
    require('selenium-download').ensure(BINPATH, function(error) {
      if (error) throw new Error(error.stack); // no point continuing so exit!
      console.log('✔ Selenium & Chromedriver downloaded to:', BINPATH);
    });
  }
});

require('nightwatch-cucumber')({
  nightwatchClientAsParameter: true,
  /* other configuration options */
});

module.exports = {
  "output_folder" : "reports",
  "selenium" : {
    "start_process" : true,
    "server_path": BINPATH + "selenium.jar",
    "port" : 4444,
    "cli_args" : {
      "webdriver.chrome.driver" : BINPATH + "chromedriver"
    }
  },

  "test_settings" : {
    "default" : {
      "launch_url" : "http://localhost",
      "selenium_port"  : 4444,
      "selenium_host"  : "localhost",
      "silent": true,
      "screenshots" : {
        "enabled" : false,
        "path" : ""
      },
      "desiredCapabilities": {
        "browserName": "chrome",
        "marionette": true
      }
    }
  }
};

function padLeft (count) { // theregister.co.uk/2016/03/23/npm_left_pad_chaos/
  return count < 10 ? '0' + count : count.toString();
}

var FILECOUNT = 0; // "global" screenshot file count
/**
 * The default is to save screenshots to the root of your project even though
 * there is a screenshots path in the config object above! ... so we need a
 * function that returns the correct path for storing our screenshots.
 * While we're at it, we are adding some meta-data to the filename, specifically
 * the Platform/Browser where the test was run and the test (file) name.
 */
function imgpath (browser) {
  var a = browser.options.desiredCapabilities;
  var meta = [a.platform];
  meta.push(a.browserName ? a.browserName : 'any');
  meta.push(a.version ? a.version : 'any');
  meta.push(a.name); // this is the test filename so always exists.
  var metadata = meta.join('~').toLowerCase().replace(/ /g, '');
  return SCREENSHOT_PATH + metadata + '_' + padLeft(FILECOUNT++) + '_';
}

module.exports.imgpath = imgpath;
module.exports.SCREENSHOT_PATH = SCREENSHOT_PATH;
```

**stack trace**
```
ERROR Error: Cannot find module '/Users/artur/Projects/cucumber/node_modules/cucumber/lib/cucumber'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/artur/Projects/cucumber/node_modules/nightwatch-cucumber/lib/peer-require.js:13:10)
    at Object.<anonymous> (/Users/artur/Projects/cucumber/node_modules/nightwatch-cucumber/lib/cucumber-api.js:13:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
There was an error while starting the test runner:

Error: No testing environment specified.
    at Object.parseTestSettings (/Users/artur/Projects/cucumber/node_modules/nightwatch/lib/runner/cli/clirunner.js:51
4:13)
    at Object.setup (/Users/artur/Projects/cucumber/node_modules/nightwatch/lib/runner/cli/clirunner.js:49:8)
    at Object.exports.runner (/Users/artur/Projects/cucumber/node_modules/nightwatch/lib/index.js:543:17)
    at /Users/artur/Projects/cucumber/node_modules/nightwatch/bin/runner.js:11:16
    at Object.exports.cli (/Users/artur/Projects/cucumber/node_modules/nightwatch/lib/index.js:537:5)
    at Object.<anonymous> (/Users/artur/Projects/cucumber/node_modules/nightwatch/bin/runner.js:9:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Please tell us about your environment:**
macOs 10.12.1
* **nightwatch-cucumber version:**
5.6.6
* **nightwatch version:**
0.9.8
* **cucumber version:**
2.0.0-rc.1
* **Node.js version:**
6.9.1

**Comment by ChrisRM** [comment]
Same here

**Comment by mucsi96** [comment]
Hi @arozwalak ! Thanks for the feedback! Cucumber just released a new major version. Currently it is not supported. I want to add support for it asap. Thank @ChrisRM for help!

**Comment by arozwalak** [comment]
cool, thanks @ChrisRM and @mucsi96. I'll downgrade cucumber for now and I'll be looking for updates ;)

**Comment by mucsi96** [comment]
@arozwalak @ChrisRM nightwatch-cucumber 6.0.0 is here with the support of cucumber 2 https://twitter.com/mucsi96/status/805447608986640384

**Comment by arozwalak** [comment]
that's a great news, thanks @mucsi96
