### ISSUE TITLE
Tests are not running when an empty feature file is included

### ISSUE THREAD

**Issue by JonWallsten** [mucsi96/nightwatch-cucumber#160]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
Test is not launched if you have an empty feature file

**Expected/desired behavior**
Test should ignore the empty file and start the test cases in the other feature files

**Reproduction of the problem**
Just create an empty file and include it in the features-folder

```
TypeError: Cannot read property 'description' of undefined
    at new Feature (C:\my_path\node_modules\cucumber\lib\models\feature.js:8:33)
    at Function.parse (C:\my_path\node_modules\cucumber\lib\cli\feature_parser.js:17:14)
    at _callee2$ (C:\my_path\node_modules\cucumber\lib\cli\helpers.js:23:52)
    at tryCatch (C:\my_path\node_modules\regenerator-runtime\runtime.js:64:40)
    at Generator.invoke [as _invoke] (C:\my_path\node_modules\regenerator-runtime\runtime.js:355:22)
    at Generator.prototype.(anonymous function) [as next] (C:\my_path\node_modules\regenerator-runtime\runtime.js:116:21)
    at step (C:\my_path\node_modules\cucumber\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\my_path\node_modules\cucumber\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```

**What is the expected behavior?**
The tests should not stop

**What is the motivation / use case for changing the behavior?**
Sometimes you want to comment out features for testing purposes

**Please tell us about your environment:**
Win 10 x64
* **nightwatch-cucumber version:**
6.1.1
* **nightwatch version:**
0.9.9
* **cucumber version:**
2.0.0-rc2
* **Node.js version:**
7.2.0

**Comment by mucsi96** [comment]
Hi @JonWallsten! Thanks for the feedback! Can you help with fixing that? I am rather busy nowadays.

**Comment by JonWallsten** [comment]
I'll do some investigation!

**Comment by JonWallsten** [comment]
https://github.com/cucumber/cucumber-js/issues/697

**Comment by mucsi96** [comment]
Thank for the investigation! Closing this
