### ISSUE TITLE
Permission issue running demo, cannot read source folder /var/folders/xx...

### ISSUE THREAD

**Issue by Geczy** [mucsi96/nightwatch-cucumber#209]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
```

```
$ nightwatch - default
Starting selenium server... started - PID:  3270

There was an error while starting the test runner:

Error: Cannot read source folder: /var/folders/l3/r22tbspn7kj0qxwhzzwy5f480000gn/T/tmp-3269DkAMVmqIzMCa/-.js
    at /usr/local/lib/node_modules/nightwatch/lib/runner/run.js:200:21
    at /usr/local/lib/node_modules/nightwatch/lib/runner/walk.js:97:18
    at FSReqWrap.oncomplete (fs.js:114:15)
```

I'm running the google babel demo. 

**Please tell us about your environment:**

```
  "devDependencies": {
    "chromedriver": "^2.28.0",
    "cucumber": "2.0.0-rc.9",
    "enzyme": "^2.8.0",
    "nightwatch": "^0.9.14",
    "nightwatch-cucumber": "^7.1.0",
    "phantomjs-prebuilt": "^2.1.14",
    "react-scripts": "0.9.5",
    "selenium-server-standalone-jar": "^3.3.1"
  },
```

node 7.8.0, npm 4.2.0

**Comment by Geczy** [comment]
Tried running with sudo, same error except the source folder changes to /tmp/xxx

**Comment by Geczy** [comment]
My nightwatch.conf.js file

```jsx
const seleniumServer = require('selenium-server')
const phantomjs = require('phantomjs-prebuilt')
const chromedriver = require('chromedriver')

require('nightwatch-cucumber')({
    cucumberArgs: ['--compiler', 'js:babel-preset-react-app', '--require', 'timeout.js', '--require', 'features/step_definitions', '--format', 'pretty', '--format', 'json:reports/cucumber.json', 'features']
})

module.exports = {
    output_folder: 'reports',
    custom_assertions_path: '',
    live_output: false,
    disable_colors: false,
    selenium: {
        start_process: true,
        server_path: seleniumServer.path,
        log_path: '',
        host: '127.0.0.1',
        port: 4444
    },
    test_settings: {
        default: {
            launch_url: 'http://localhost:8087',
            selenium_port: 4444,
            selenium_host: '127.0.0.1',
            desiredCapabilities: {
                browserName: 'phantomjs',
                javascriptEnabled: true,
                acceptSslCerts: true,
                'phantomjs.binary.path': phantomjs.path
            }
        },
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome',
                javascriptEnabled: true,
                acceptSslCerts: true
            },
            selenium: {
                cli_args: {
                    'webdriver.chrome.driver': chromedriver.path
                }
            }
        },
        firefox: {
            desiredCapabilities: {
                browserName: 'firefox',
                javascriptEnabled: true,
                acceptSslCerts: true
            }
        }
    }
}
```

**Comment by Geczy** [comment]
Can delete

**Comment by AlfredoMoretta** [comment]
sorry Geczy how you solved it?
Thank you

**Comment by RazvanVuscan** [comment]
I managed to overcome the error by running "nightwatch --config nightwatch.conf.js" in the folder where nightwatch.conf.js rests along with the "features" and "feature/steps_definitions" folders. I get this instead now: "TypeError: Cannot read property 'api' of undefined".

**Comment by JairoAparicio** [comment]
'nightwatch', '--', '--group', "$testSuite", '--env', "$projectEnv"]
Hi There, I resolve the issue "Error: Cannot read source folder: /..."
Executing the command in this two ways:
nightwatch -- --group testSuite --env nameEnv
nightwatch -- --test  testsFile/testSuite --env default
Keep in mind  the double argument lines : "-- --group" runner,js resolve in this way.
replace the group or fil test in you project and review the test Seeting in nighwatch.json to resolve the parameter --env or -e.
