### ISSUE TITLE
Error: No tests defined when used with gulp-nightwatch

### ISSUE THREAD

**Issue by subhojit777** [mucsi96/nightwatch-cucumber#230]
```
[ x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
I am getting error:

```
There was an error while starting the test runner:
Error: No tests defined! using source folder: /tmp/tmp-19wODo22pfsHgW/features
    at /home/node/node_modules/nightwatch/lib/runner/run.js:213:20
    at /home/node/node_modules/nightwatch/lib/runner/walk.js:161:15
    at /home/node/node_modules/nightwatch/lib/runner/walk.js:76:13
    at FSReqWrap.oncomplete (fs.js:123:15)
[09:58:09] 'task1' errored after 4.19 s
[09:58:09] Error in plugin 'gulp-nightwatch'
Message:
    nightwatch exited with code 1
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
[09:58:09] 'default' errored after 4.2 s
[09:58:09] The following tasks did not complete: task2
[09:58:09] Did you forget to signal async completion?
```
when executing the tests using [`gulp-nightwatch`](https://github.com/tatsuyafw/gulp-nightwatch).

### `gulpfile.js`
```js
var gulp = require('gulp');
var gulpNightwatch = require('gulp-nightwatch');

gulp.task('task1', function(done) {
  return gulp.src('gulpfile.js')
    .pipe(gulpNightwatch({
      configFile: 'nightwatch.conf.js',
      cliArgs: {
        env: 'prod',
        tag: 'task1',
      }
    }));
});

gulp.task('task2', function(done) {
  return gulp.src('gulpfile.js')
    .pipe(gulpNightwatch({
      configFile: 'nightwatch.conf.js',
      cliArgs: {
        env: 'prod',
        tag: 'task2',
      }
    }));
});

gulp.task('default', gulp.parallel('task1', 'task2', function(done) {
  done();
}));
```

**Expected/desired behavior**
Should run the tests normally.

**What is the expected behavior?**
Should run the tests normally.

**Please tell us about your environment:**

* **nightwatch-cucumber version:**
nightwatch-cucumber@7.1.7

* **nightwatch version:**
nightwatch@0.9.15

* **cucumber version:**
cucumber@2.2.0

* **Node.js version:**
v6.10.2

* **npm version:**
3.10.10

* **gulp-cli version:**
gulp-cli@1.3.0

* **gulp version:**
gulp@4.0.0-alpha.2 (git://github.com/gulpjs/gulp.git#38246c3f8b6dbb8d4ef657183e92d90c8299e22f)

**Comment by subhojit777** [comment]
nevermind.. there was something wrong in my docker setup. Files not mounting properly. It is working with the above `gulpfile.js`
