### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by vpetrache** [mucsi96/nightwatch-cucumber#235]
Hey,

I'm getting 

nightwatch.conf.js

`
require('nightwatch-cucumber')({
  cucumberArgs: [
    '--require', 'timeout.js',
    '--require', 'cucumber/featureFiles/step_definitions',
    '--format', 'pretty',
    '--format', 'json:test_data/report/cucumber_report.json',
    'cucumber/featureFiles']
    });
`

steps:

`
const {client} = require('nightwatch-cucumber');

When(/^the session expires for "([^"]*)"$/, function (arg1) {

   client.getUrl().then((r) =>
     {console.log(r);
     currentPageURL = r.value;
     });

     return console.log(currentPageURL);

  });

`

Result is:

`
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'value' of undefined
    at client.url.then (D:\Projects\paywall-testing\nodejs\cucumber\featureFiles\step_definitions\ui_global_steps.js:86:23)
    at process._tickCallback (internal/process/next_tick.js:109:7) } reason: TypeError: Cannot read property 'value' of undefined
    at client.url.then (D:\Projects\paywall-testing\nodejs\cucumber\featureFiles\step_definitions\ui_global_steps.js:86:23)
    at process._tickCallback (internal/process/next_tick.js:109:7)
`

I'm trying to get the current page url for a REST call.

**Comment by mucsi96** [comment]
Please try to add a `return` before `client.getUrl` as step definition should return a client. See [docs](https://github.com/mucsi96/nightwatch-cucumber#step-definition-handling)
