### ISSUE TITLE
nightwatch-cucumber exit code always zero

### ISSUE THREAD

**Issue by SitCode1993** [mucsi96/nightwatch-cucumber#259]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
nightwatch-cucumber always have an exit code of zero even when there are some scenarios failing

**Expected/desired behavior**
upon failure scenarios, nightwatch-cucumber should have an exit code of non-zero

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://c9.io, http://www.koding.com, https://www.nitrous.io or similar.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* output of the following command from your project root `npm ls nightwatch cucumber nightwatch-cucumber && node --version`

**Comment by SitCode1993** [comment]
I'm using nightwatch-cucumber 7.1.11

**Comment by mucsi96** [comment]
Hi @SitCode1993! Thanks for your feedback! I have a passing test case for returning correct status code. So I do not really understand the issue. I need a complete minimal project where I can reproduce the issue. Please attach it as ZIP archive.

**Comment by SitCode1993** [comment]
Hi @mucsi96, due to my company governance and compliance I can't share the actual provide, but below are the logs showing some of the scenarios failing but the exit code still returning as 0.

 ✔ And the user clicks the Deferred tab
  ✔ And the user clicks the Leads tab
{ AssertionError: 'In progress' == 'New'
    at Object.<anonymous> (/Users/nerdy/Documents/money-machine-web/features/step_definitions/common_steps.js:27:28)
    at HttpRequest.<anonymous> (/Users/nerdy/Documents/money-machine-web/node_modules/nightwatch/lib/index.js:366:18)
    at emitTwo (events.js:106:13)
    at HttpRequest.emit (events.js:191:7)
    at HttpRequest.<anonymous> (/Users/nerdy/Documents/money-machine-web/node_modules/nightwatch/lib/index.js:382:15)
    at emitThree (events.js:116:13)
    at HttpRequest.emit (events.js:194:7)
    at IncomingMessage.<anonymous> (/Users/nerdy/Documents/money-machine-web/node_modules/nightwatch/lib/http/request.js:166:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'AssertionError',
  actual: 'In progress',
  expected: 'New',
  operator: '==',
  message: '\'In progress\' == \'New\'',
  generatedMessage: true }
  ✖ Then a list of sub-tabs is displayed:
      | New         |
      | In progress |
      | Sales       |
      | No sales    |
      | Reassigned  |
      | Deferred    |
  - And the Date drop-down and Interval selector are displayed
  - And the Interval selector is defaulted to Year
  - And the Month date drop down is displayed
  - When the user clicks the Week tab on the Interval selector
  - Then the Week date drop down is displayed
  - When the user clicks the Quarter tab on the Interval selector
  - Then the Quarter date drop down is displayed
  - When the user clicks the Year tab on the Interval selector
  - Then the Year date drop down is displayed
  - And the table header should be Leads deferred within branch
  - And a table with three columns, Amount, Adviser name and Consultant code as headers is displayed

Failures:

1) Scenario: User checks the DEFERRED LEADS the BUSINESS VIEW - features/Activity_Deferred.feature:4
   Step: Then a list of sub-tabs is displayed: - features/Activity_Deferred.feature:9
   Step Definition: features/step_definitions/common_steps.js:21
   Message:
     AssertionError: 'In progress' == 'New'
         + expected - actual

         -In progress
         +New
     
         at Object.<anonymous> (/Users/nerdy/Documents/money-machine-web/features/step_definitions/common_steps.js:27:28)
         at HttpRequest.<anonymous> (/Users/nerdy/Documents/money-machine-web/node_modules/nightwatch/lib/index.js:366:18)
         at emitTwo (events.js:106:13)
         at HttpRequest.emit (events.js:191:7)
         at HttpRequest.<anonymous> (/Users/nerdy/Documents/money-machine-web/node_modules/nightwatch/lib/index.js:382:15)
         at emitThree (events.js:116:13)
         at HttpRequest.emit (events.js:194:7)
         at IncomingMessage.<anonymous> (/Users/nerdy/Documents/money-machine-web/node_modules/nightwatch/lib/http/request.js:166:16)
         at emitNone (events.js:91:20)
         at IncomingMessage.emit (events.js:185:7)
         at endReadableNT (_stream_readable.js:974:12)
         at _combinedTickCallback (internal/process/next_tick.js:80:11)
         at process._tickCallback (internal/process/next_tick.js:104:9)

1 scenario (1 failed)
16 steps (1 failed, 11 skipped, 4 passed)
0m35.053s

Process finished with exit code 0

**Comment by mucsi96** [comment]
Unfortunatly it is not possible to debug the issue only with a provided log. Please create a small separate dummy project where you are able to reproduce the issue

**Comment by SitCode1993** [comment]
Hi @mucsi96 , thanks for the swift response, Ive created a dummy project you can check the attached zip file.

[dummy1.zip](https://github.com/mucsi96/nightwatch-cucumber/files/1222292/dummy1.zip)

**Comment by mucsi96** [comment]
Thanks! Checking...

**Comment by mucsi96** [comment]
Ok. So I have found the issue: When I run the test the execution hangs, because there is uncaught exception thrown by `assert` module. Unfortunately you cannot use `chai` or `assert` as Nightwatch assertions are working in a different (strange manner). After changing the code to use Nightwatch assertions it works fine. http://nightwatchjs.org/api#assert-title

**Comment by SitCode1993** [comment]
@mucsi96 thank you very much, I will change all my asserts to use nightwatch asserts rather, thank you
