### ISSUE TITLE
Getting error "Rejection at: Promise Promise {   <rejected> TypeError: Cannot read property 'indexOf' of undefined"

### ISSUE THREAD

**Issue by deepak2020** [mucsi96/nightwatch-cucumber#316]
**I'm submitting a ...**  (check one with "x")
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'indexOf' of undefined
    at C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch\lib\runner\run.js:184:10
    at Array.map (<anonymous>)
    at Function.Runner.readPaths (C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch\lib\runner\run.js:183:30)
    at Runner.runner (C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch\lib\runner\run.js:235:10)
    at Runner.<anonymous> (C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch-cucumber\lib\nightwatch-api.js:317:32)
    at Generator.next (<anonymous>)
    at onFulfilled (C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch-cucumber\node_modules\co\index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } reason: { TypeError: Cannot read property 'indexOf' of undefined
    at C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch\lib\runner\run.js:184:10
    at Array.map (<anonymous>)
    at Function.Runner.readPaths (C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch\lib\runner\run.js:183:30)
    at Runner.runner (C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch\lib\runner\run.js:235:10)
    at Runner.<anonymous> (C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch-cucumber\lib\nightwatch-api.js:317:32)
    at Generator.next (<anonymous>)
    at onFulfilled (C:\Users\deepak.kumar\Nightwatch_Demo\nightwatch-cucumber-example\node_modules\nightwatch-cucumber\node_modules\co\index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  [Symbol(originalCallSite)]:
   [ CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {} ],
  [Symbol(mutatedCallSite)]:
   [ CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {},
     CallSite {} ] }

[ ] bug report
**Current behavior**
After executing a feature file I get result stating - 1 scenario (1 passed)
1 step (1 passed)
0m21.339s
 But then after that I get the above error and need to be stopped manually.

**Expected/desired behavior**
Ideally it should stop after feature execution.

**Reproduction of the problem**
Not sure how to create a demo project to reproduce the issue.

Nightwatch.conf.js file for your reference

`const seleniumServer = require('selenium-server');
const phantomjs = require('phantomjs-prebuilt');
const chromedriver = require('chromedriver');
const geckodriver = require('geckodriver');
var nightwatchCucumber = require('nightwatch-cucumber');

var nightwatchCucumberConf = {
    runner: 'nightwatch',
    featureFiles: 'features',
    htmlReport: './reports/index.html'

    }
module.exports = {
    src_folders: [nightwatchCucumber(nightwatchCucumberConf)],
    page_objects_path: ['forms','modules', 'pages'],
    custom_commands_path:'',
    test_workers: false,
    output_folder: false,
    custom_assertions_path: '',
    globals_path : '',
    parallel_process_delay : 10,
    live_output: true,
    disable_colors: false,
    selenium: {
        start_process: true,
        server_path: 'node_modules/selenium-server/lib/runner/selenium-server-standalone-3.5.3.jar',
        log_path: '',
        host: '127.0.0.1',
        port: 4040
    },
    test_settings: {
        default: {
            launch_url: 'http://ondemand.sauculabs.com:80',
            selenium_port: 80,
            selenium_host: 'ondemand.saucelabs.com',
            silent: true,
            username: 'pyneema',
            access_key: 'xxxxx-xxxx-xxxxx-xxxxx',
                        globals: {
                waitForConditionTimeout: 10000,
            },
        },
        chrome: {
            desiredCapabilities: {
                browserName: 'chrome',
                javascriptEnabled: true,
                acceptSslCerts: true,
                elementScrollBehavior: 1
            },
            selenium: {
                cli_args: {
                    'webdriver.chrome.driver': 'node_modules/chromedriver/lib/chromedriver/chromedriver'
                }
            }
        },
        firefox: {
            desiredCapabilities: {
                browserName: 'firefox',
            }
        }
    }
};`

**Comment by mucsi96** [comment]
Please remove src_folders from config as described in the docs

**Comment by deepak2020** [comment]
Thank you so much! It really worked was struggling for last few days. You can close the issue.
