### ISSUE TITLE
Run scenario by name or row number from the feature file

### ISSUE THREAD

**Issue by vpetrache** [mucsi96/nightwatch-cucumber#325]
**Current behavior**
How can I run a scenario by it's name or by the row number from the feature file? 
Ex. cucumber features/test.feature:7

**Expected/desired behaviour**
The specified scenario should run.

**Reproduction of the problem**
Please create a minimal demo application where the issue can be reproduced. You can upload it to your GitHub account or attach it as ZIP archive (please make sure you exclude the `node_modules` folder from the archive). As a base you can use the [nightwatch-example](https://github.com/mucsi96/nightwatch-example) repository.

add cucumberArgs in nightwatch.conf.js

require('nightwatch-cucumber')({
    cucumberArgs: [
        '--require', 'timeout.js',
        '--require', 'cucumber/featureFiles/step_definitions',
        '--format', 'json:report/cucumber_report.json',
        "--strict",
        'cucumber/featureFiles/1-Assets.feature:7']
});

And execute the Test Runner

**What is the motivation / use case for changing the behaviour?**

To run failed tests from rerun cucumber format.

**Please tell us about your environment:**
In case of a bug report please provide the following information:
* output of the following command from your project root `npm ls nightwatch cucumber nightwatch-cucumber && node --version`
* output of running nightwatch with `--verbose` flag

/usr/local/bin/node /Users/valentinpetrache/Documents/demo/node_modules/nightwatch/bin/runner.js --config nightwatch.conf.js -e local --tag assets --debug

ERROR Error: Feature source cucumber/featureFiles/1-Assets.feature:7:15 doesn't exists
    at featureFiles.forEach (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch-cucumber/lib/runner.js:99:15)
    at Array.forEach (<anonymous>)
    at Runner.run (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch-cucumber/lib/runner.js:95:23)
    at module.exports (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch-cucumber/lib/index.js:15:10)
    at Object.<anonymous> (/Users/valentinpetrache/Documents/demo/nightwatch.conf.js:5:31)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at CliRunner.readSettings (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch/lib/runner/cli/clirunner.js:87:23)
    at CliRunner.setup (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch/lib/runner/cli/clirunner.js:48:8)
    at Object.exports.runner (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch/lib/index.js:551:17)
    at /Users/valentinpetrache/Documents/demo/node_modules/nightwatch/bin/runner.js:10:16
There was an error while starting the test runner:

Error: No testing environment specified.
    at CliRunner.parseTestSettings (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch/lib/runner/cli/clirunner.js:515:13)
    at CliRunner.setup (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch/lib/runner/cli/clirunner.js:49:8)
    at Object.exports.runner (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch/lib/index.js:551:17)
    at /Users/valentinpetrache/Documents/demo/node_modules/nightwatch/bin/runner.js:10:16
    at Object.exports.cli (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch/lib/index.js:545:5)
    at Object.<anonymous> (/Users/valentinpetrache/Documents/demo/node_modules/nightwatch/bin/runner.js:8:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by mucsi96** [comment]
I think this is described in the docs. http://mucsi96.github.io/nightwatch-cucumber/#executing-individual-feature-files-or-scenarios. Do I miss something?
