### ISSUE TITLE
Error running tests in Windows with absolute feature directories

### ISSUE THREAD

**Issue by aquilax** [mucsi96/nightwatch-cucumber#326]
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
Running tests generates error.

**Expected/desired behavior**
Tests to run.

**Reproduction of the problem**
In the configuration, pass absolute path(s) to features' directories.
Example:
```js
  { cucumberArgs:
   [ '--format',
     'json:./reports/cucumber.json',
     '--require',
     'C:\\temp\\my-package\\tests\\node_modules\\package2\\lib\\core\\timeout.js',
     '--require',
     'C:\\temp\\my-package\\tests\\node_modules\\package3\\hooks\\hooks.js',
     '--require',
     'C:\\temp\\my-package\\tests\\node_modules\\package3\\step_definitions\\generic',
     '--require',
     'C:\\temp\\my-package\\tests\\node_modules\\package3\\step_definitions\\desktop',
     '--format',
     'node_modules/cucumber-pretty',
     'C:\\temp\\my-package\\tests\\features',
     'C:\\temp\\my-package\\tests\\node_modules\\package3\\features',
 ] }
```

This causes the following error:
```
ERROR Error: EEXIST: file already exists, mkdir 'C:\Users\USER_NAME\AppData\Local\Temp\tmp-18176MwC3VUGZcjb9'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (C:\temp\my-package\node_modules\mkdirp\index.js:71:13)
    at sync (C:\temp\my-package\node_modules\mkdirp\index.js:77:24)
...
```
I need to run tests suites spread in different node packages, that's why I am passing absolute paths to all tests' locations. The setup works fine in Linux but not on Windows.

I believe the issue is in two locations in `runner.js`:

https://github.com/mucsi96/nightwatch-cucumber/blob/master/lib/runner.js#L105
https://github.com/mucsi96/nightwatch-cucumber/blob/master/lib/runner.js#L170

Where the feature directory/path file is joined with the dummy path. In case of Windows and absolute paths, this produces the original dummy path.

A possible workaround is the turn absolute paths to relative ones.

**What is the motivation / use case for changing the behavior?**
Running tests with absolute paths should work on Windows.

**Please tell us about your environment:**
Windows 10
```
my-package@1.0.0 C:\temp\my-package\tests
`-- my-package@1.0.0
  +-- nightwatch@0.9.16
  `-- nightwatch-cucumber@8.2.11

v8.9.3
```

**Comment by aquilax** [comment]
Will try to submit a pull request today.
